### ISSUE TITLE
[npm] missing script: download:extensions

### ISSUE THREAD

**Issue by tyn1998** [opensumi/opensumi-module-samples#1]
`npm install`时，会触发`npm prepare`，其中“download:extensions”在package.json的`scripts`中不存在。

https://github.com/opensumi/opensumi-module-samples/blob/389d516555c498167896794d18c84315f3f21933/package.json#L8-L17

错误截图：
<img width="1315" alt="image" src="https://user-images.githubusercontent.com/32434520/170433144-9c809f8e-8e67-4ec7-a37e-69ab24069306.png">

**Comment by erha19** [comment]
这个应该是例子迁移时遗留的，实际上这部分案例主要以代码案例为主，可以去掉 download:extensions

**Comment by tyn1998** [comment]
嗯~为了代码跳转，所以npm install了，包都成功装上了的。

**Comment by erha19** [comment]
fixed #2.
