### ISSUE TITLE
想了解一下项目用的node，npm版本

### ISSUE THREAD

**Issue by 0214ggyy** [opensumi/opensumi-module-samples#33]
node： v18.19.0
npm：10.2.3
无法安装node_modules

 
![image](https://github.com/opensumi/opensumi-module-samples/assets/45169483/1020d8dc-e4b7-404e-9cb4-27e936cabed8)

**Comment by bytemain** [comment]
这个是因为 webpack4 不支持 openssl 新版，

可以降级到 node16 或者配一个参数：

```
export NODE_OPTIONS=--openssl-legacy-provider
```

可参考：
- https://github.com/webpack/webpack/issues/14532

**Comment by 0214ggyy** [comment]
在欢乐时，朋友们会认识我们；在患难时，我们会认识朋友。谢谢，来信！！！
