### ISSUE TITLE
能提供一下node版本和npm 版本吗？

### ISSUE THREAD

**Issue by 0214ggyy** [opensumi/opensumi-module-samples#34]
![image](https://github.com/opensumi/opensumi-module-samples/assets/45169483/d850e490-8242-4d76-9e85-feaa2fce72e5)

window更换了好几个版本都无法下载依赖成功

**Comment by erha19** [comment]
@0214ggyy 目前日常使用的版本是 node16，你这里看起来像是部分依赖安装存在问题，你可以 node_modules 删了，看一下重新安装过程是否有报错

**Comment by bytemain** [comment]
已经在另一个 issue 中回复你了：
- https://github.com/opensumi/opensumi-module-samples/issues/33

**Comment by 0214ggyy** [comment]
在欢乐时，朋友们会认识我们；在患难时，我们会认识朋友。谢谢，来信！！！
